# Generated by Django 3.0.5 on 2020-06-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='property_type',
        ),
    ]
